/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGithubSearchRouteImport } from './routes/api/github-search'
import { Route as ApiLmRouteImport } from './routes/api/lm'
import { Route as ApiReviewRouteImport } from './routes/api/review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubSearchRoute = ApiGithubSearchRouteImport.update({
  id: '/api/github-search',
  path: '/api/github-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLmRoute = ApiLmRouteImport.update({
  id: '/api/lm',
  path: '/api/lm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewRoute = ApiReviewRouteImport.update({
  id: '/api/review',
  path: '/api/review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/github-search': typeof ApiGithubSearchRoute
  '/api/lm': typeof ApiLmRoute
  '/api/review': typeof ApiReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/github-search': typeof ApiGithubSearchRoute
  '/api/lm': typeof ApiLmRoute
  '/api/review': typeof ApiReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/github-search': typeof ApiGithubSearchRoute
  '/api/lm': typeof ApiLmRoute
  '/api/review': typeof ApiReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/github-search' | '/api/lm' | '/api/review'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/github-search' | '/api/lm' | '/api/review'
  id: '__root__' | '/' | '/api/github-search' | '/api/lm' | '/api/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGithubSearchRoute: typeof ApiGithubSearchRoute
  ApiLmRoute: typeof ApiLmRoute
  ApiReviewRoute: typeof ApiReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-search': {
      id: '/api/github-search'
      path: '/api/github-search'
      fullPath: '/api/github-search'
      preLoaderRoute: typeof ApiGithubSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lm': {
      id: '/api/lm'
      path: '/api/lm'
      fullPath: '/api/lm'
      preLoaderRoute: typeof ApiLmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review': {
      id: '/api/review'
      path: '/api/review'
      fullPath: '/api/review'
      preLoaderRoute: typeof ApiReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGithubSearchRoute: ApiGithubSearchRoute,
  ApiLmRoute: ApiLmRoute,
  ApiReviewRoute: ApiReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
